/**
 * Check that token measurements and served-message bytes remain equal across
 * plugin revisions and across a cached-prefix rebuild/restart. The driver runs
 * the real TS transform through cold/defer, a forced render-epoch rebuild, and
 * a separate-process restart. No OpenCode host, provider, historian or live
 * store is used. Give each revision a different throwaway root, but reuse that
 * revision's root between seed and restart so the durable cache survives.
 * Compare the JSON artifacts generated by the two source revisions.
 *
 * bun scripts/perf-audit/issue-653-review-cycle.ts --root <TMPDIR/magic-context/...>
 *   --src <plugin src> --phase seed|restart --out <artifact.json>
 */
import { createHash } from "node:crypto";
import { lstatSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { buildSession, loadMessages } from "./issue-653-fixture";
import { providerVisibleMessage } from "../../src/hooks/magic-context/provider-visible-parts";

const args = process.argv.slice(2);
const flag = (name: string): string => {
    const index = args.indexOf(name);
    const value = index < 0 ? undefined : args[index + 1];
    if (!value) throw new Error(`${name} is required`);
    return value;
};
const root = resolve(flag("--root"));
if (!root.startsWith(`${resolve(tmpdir(), "magic-context")}/`)) {
    throw new Error("--root must be beneath TMPDIR/magic-context/");
}
mkdirSync(root, { recursive: true });
if (!realpathSync(root).startsWith(`${realpathSync(tmpdir())}/magic-context/`)) {
    throw new Error("--root must not resolve outside TMPDIR/magic-context/");
}
for (const [name, directory] of [
    ["XDG_DATA_HOME", "data"], ["XDG_CONFIG_HOME", "config"],
    ["XDG_STATE_HOME", "state"], ["XDG_RUNTIME_DIR", "runtime"],
    ["XDG_CACHE_HOME", "cache"], ["HOME", "home"],
    ["MAGIC_CONTEXT_STORAGE_DIR", "storage"],
] as const) {
    const path = join(root, directory);
    mkdirSync(path, { recursive: true });
    if (!realpathSync(path).startsWith(`${realpathSync(root)}/`)) {
        throw new Error(`environment directory escapes throwaway root: ${name}`);
    }
    process.env[name] = path;
}
process.env.OPENCODE_DB = join(root, "opencode.db");
for (const base of [process.env.OPENCODE_DB, join(root, "storage/context.db"), join(root, "storage/store.db")]) {
    for (const suffix of ["", "-wal", "-shm"]) {
        const path = `${base}${suffix}`;
        const stat = lstatSync(path, { throwIfNoEntry: false });
        if (stat && (stat.isSymbolicLink() || stat.nlink !== 1)) {
            throw new Error(`aliased SQLite file is not allowed: ${path}`);
        }
    }
}
const src = resolve(flag("--src"));
const phase = flag("--phase");
if (phase !== "seed" && phase !== "restart") throw new Error("unknown phase");
const out = resolve(flag("--out"));
const imp = async <T>(path: string): Promise<T> => await import(`${src}/${path}`) as T;
// Fixed wall time keeps TTLs and synthetic-message timestamps equal across the
// paired runs; history, message IDs, diagnostic payload and compartment are fixed.
Date.now = () => 1_791_633_600_000;
const { openDatabase, closeDatabase, getOrCreateSessionMeta } = await imp<
    typeof import("../../src/features/magic-context/storage")
>("features/magic-context/storage.ts");
const { appendCompartments } = await imp<typeof import("../../src/features/magic-context/compartment-storage")>("features/magic-context/compartment-storage.ts");
const { createTagger } = await imp<typeof import("../../src/features/magic-context/tagger")>("features/magic-context/tagger.ts");
const { createMessagesTransformHandler } = await imp<typeof import("../../src/plugin/messages-transform")>("plugin/messages-transform.ts");
const { createTransform } = await imp<typeof import("../../src/hooks/magic-context/transform")>("hooks/magic-context/transform.ts");
const { refreshModelLimitsFromApi } = await imp<typeof import("../../src/shared/models-dev-cache")>("shared/models-dev-cache.ts");
const { setLogLineForwarder } = await imp<typeof import("../../src/shared/logger")>("shared/logger.ts");
const { getInMemorySlot } = await imp<typeof import("../../src/hooks/magic-context/lkg-slot")>("hooks/magic-context/lkg-slot.ts");
const { measureTailHygiene } = await imp<typeof import("../../src/hooks/magic-context/tail-hygiene-walk")>("hooks/magic-context/tail-hygiene-walk.ts");
const { buildTrueRawTokenIndex } = await imp<typeof import("../../src/hooks/magic-context/read-session-true-raw-tokens")>("hooks/magic-context/read-session-true-raw-tokens.ts");
const { computeM0BlockTokens } = await imp<typeof import("../../src/hooks/magic-context/m0-token-breakdown")>("hooks/magic-context/m0-token-breakdown.ts");
const { Database } = await imp<typeof import("../../src/shared/sqlite")>("shared/sqlite.ts");
const { OPENCODE1_MESSAGE_PART_SCHEMA } = await imp<typeof import("../../src/features/magic-context/__tests__/opencode1-query-fixture")>("features/magic-context/__tests__/opencode1-query-fixture.ts");
const session = buildSession("review653", 653, 40, 1024 * 1024, "lsp-metadata");
const raw = loadMessages(session) as Array<{
    info: { id: string; sessionID: string; role: "user" | "assistant"; time: { created: number } } & Record<string, unknown>;
    parts: Array<Record<string, unknown>>;
}>;
const hostDb = new Database(process.env.OPENCODE_DB);
if (phase === "seed") {
    hostDb.exec(OPENCODE1_MESSAGE_PART_SCHEMA);
    const insertMessage = hostDb.prepare("INSERT INTO message VALUES (?, ?, ?, ?, ?)");
    const insertPart = hostDb.prepare("INSERT INTO part VALUES (?, ?, ?, ?, ?, ?)");
    for (const message of raw) {
        const { id, sessionID: _session, ...info } = message.info;
        const created = message.info.time.created;
        insertMessage.run(id, session.sessionId, created, created, JSON.stringify(info));
        for (const part of message.parts) {
            const { id: partId, sessionID: _s, messageID: _m, ...data } = part;
            insertPart.run(partId, id, session.sessionId, created, created, JSON.stringify(data));
        }
    }
}
const db = openDatabase()!;
if (!db) throw new Error("throwaway plugin DB did not open");
getOrCreateSessionMeta(db, session.sessionId);
if (phase === "seed") {
    appendCompartments(db, session.sessionId, [{
        sequence: 1, startMessage: 1, endMessage: 1,
        startMessageId: raw[0]!.info.id, endMessageId: raw[0]!.info.id,
        title: "Fix build and validate edits", content: "Updated TypeScript imports and ran checks.",
        p1: "Updated TypeScript imports and ran checks.",
    }]);
}
await refreshModelLimitsFromApi({ config: { providers: async () => ({ data: { providers: [{
    id: "anthropic", models: { "claude-sonnet-4-5": { limit: { context: 1_000_000, output: 32_000 } } },
}] } }) } } as never);
const lines: string[] = [];
setLogLineForwarder((line) => { lines.push(line); });
const transform = createTransform({
    client: { session: {
        get: async () => ({ data: { directory: process.cwd() } }),
        prompt: async () => { throw new Error("offline audit must not invoke historian"); },
    } },
    directory: process.cwd(),
    tagger: createTagger(), scheduler: { shouldExecute: () => "defer" }, db,
    contextUsageMap: new Map([[session.sessionId, { usage: { percentage: 25, inputTokens: 250_000 }, updatedAt: Date.now() }]]),
    historyRefreshSessions: new Set(), pendingMaterializationSessions: new Set(),
    lastHeuristicsTurnId: new Map(), clearReasoningAge: 50, protectedTokens: 0,
    historianRunnable: true, channel1StateBySession: new Map(),
    liveModelBySession: new Map([[session.sessionId, { providerID: "anthropic", modelID: "claude-sonnet-4-5" }]]),
} as never);
const handler = createMessagesTransformHandler({ magicContext: { "experimental.chat.messages.transform": transform } });
const sha = (text: string) => createHash("sha256").update(text).digest("hex");
const rawIndex = buildTrueRawTokenIndex(session.sessionId, raw.map((m, index) => ({
    id: m.info.id, role: m.info.role, parts: m.parts, ordinal: index + 1,
})), { providerShapeVersion: "opencode-v1", cacheNamespace: "review653" });
const artifacts: Record<string, unknown> = {
    phase, inputCharacters: session.totalChars,
    trueRawTotals: raw.map((_, index) => rawIndex.tokenForOrdinal(index + 1)),
    suffixBoundary1000: rawIndex.findSuffixStartForTokens(1000),
    headCap1000: rawIndex.findHeadEndForCap(1, raw.length + 1, 1000),
    rawTailMeasurement: measureTailHygiene({ messages: raw as never, tags: [], protectedTagNumbers: new Set() }),
};
const passes = phase === "seed" ? ["cold", "defer", "rebuild", "after-rebuild-defer"] : ["restart-defer", "restart-second-defer"];
const results: unknown[] = [];
for (const pass of passes) {
    if (pass === "rebuild") {
        db.prepare("UPDATE session_meta SET cached_m0_upgrade_state='ready' WHERE session_id=?").run(session.sessionId);
    }
    lines.length = 0;
    const messages = loadMessages(session);
    await handler({}, { messages } as never);
    const providerView = JSON.stringify(messages.map(providerVisibleMessage));
    const cached = db.prepare("SELECT cached_m0_bytes, cached_m1_bytes, cached_m0_upgrade_state FROM session_meta WHERE session_id=?").get(session.sessionId) as { cached_m0_bytes: string | Uint8Array | null; cached_m1_bytes: string | Uint8Array | null; cached_m0_upgrade_state: string };
    if (cached.cached_m0_bytes === null) throw new Error("m[0] was not materialized");
    const decode = (bytes: string | Uint8Array | null): string => bytes instanceof Uint8Array ? Buffer.from(bytes).toString("utf8") : (bytes ?? "");
    const m0 = computeM0BlockTokens(db, session.sessionId, { m0Text: decode(cached.cached_m0_bytes), m1Text: decode(cached.cached_m1_bytes), projectIdentity: undefined, injectionBudgetTokens: undefined, memoryBlockCount: 0 });
    const slot = getInMemorySlot(session.sessionId);
    if (!slot) throw new Error(`no LKG capture on ${pass}`);
    if (pass === "rebuild" && !lines.some((line) => line.includes("compartment_render_epoch"))) {
        throw new Error("render-epoch rebuild was not reached");
    }
    results.push({ pass, providerViewSha256: sha(providerView), providerViewCharacters: providerView.length,
        rawServedSha256: sha(JSON.stringify(messages)), m0,
        upgradeState: cached.cached_m0_upgrade_state, slotStored: true,
        slotPrefixRawCharacters: slot.jsonPrefix.length,
        slotPrefixProviderViewSha256: sha(JSON.stringify(JSON.parse(slot.jsonPrefix).map(providerVisibleMessage))),
        epochRebuild: lines.some((line) => line.includes("compartment_render_epoch")),
    });
    writeFileSync(`${out}.${pass}.log`, lines.join(""));
    writeFileSync(`${out}.${pass}.provider.json`, providerView);
}
artifacts.passes = results;
const lsof = Bun.spawnSync(["lsof", "-p", String(process.pid)], { windowsHide: true });
if (lsof.exitCode !== 0) throw new Error("lsof isolation proof failed");
const dbFiles = [...new Set(lsof.stdout.toString().split("\n")
    .map((line) => line.split(/\s+/).slice(8).join(" ")).filter((path) => /\.db(-wal|-shm)?$/.test(path)))];
if (dbFiles.length === 0 || dbFiles.some((path) => !realpathSync(path).startsWith(`${realpathSync(root)}/`))) {
    throw new Error(`non-throwaway SQLite file or absent proof: ${dbFiles.join(", ")}`);
}
console.log(`pid=${process.pid} lsof .db files: ${dbFiles.join(", ")}`);
writeFileSync(out, JSON.stringify(artifacts, null, 2));
console.log(JSON.stringify({ ...artifacts, rawTailMeasurement: undefined }));
hostDb.close();
closeDatabase();
